# This is the config file for the fgt stat checker script.
# 
env_vars:
    user: "<user>"
    passwd: "<passwd>"

debug_config:
    debug_flag: "INFO" # Choices - DEBUG, INFO and NOTSET
    debug_file: "flex_keeper_debug.log"
    debug_path: "logs"
    debug_log_flag: "N" # Y for logging to file N to turn off.
